--- #YAML:1.0
name:                Perl-Critic-Pulp
version:             19
abstract:            Some add-on policies for Perl::Critic.
license:             gpl
author:              
    - Kevin Ryde <user42@zip.com.au>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::String:                    1.02
    List::Util:                    0
    Perl::Critic:                  1.082
    Perl::Critic::Utils:           0
    Perl::Critic::Utils::PPIRegexp: 0
    Perl::Critic::Violation:       0
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
optional_features:
    maximum_policies:
        description: Have the policies check as much as possible.
        requires:
            Perl::MinimumVersion: 0
    maximum_tests:
        description: Have "make test" do as much as possible.
        requires:
            Perl::MinimumVersion: 0
            Test::NoWarnings: 0
            Test::Pod: 1.00
            Test::YAML::Meta: 0
            YAML: 0
            YAML::Syck: 0
            YAML::Tiny: 0
            YAML::XS: 0
    maximum_devel:
        description: Stuff used variously for development.
        requires:
            Perl6::Slurp: 0
no_index:
    directory:
        - devel
        - inc
        - t
resources:
    homepage: http://user42.tuxfamily.org/perl-critic-pulp/index.html
    license: http://www.gnu.org/licenses/gpl.html
